### 1

In [6]:
import numpy as np
A=np.array([[2,-1],[0,3]])
B=np.array([[1,2],[-3,4]])
#Addition
X=A+B
#multiplication
Y=A*B
#subtraction
Z=3*A-2*B
#display the results
print(f"Addition:\n",X)
print(f"Multiplication:\n",Y)
print(f"Subtraction:\n",Z)


Addition:
 [[ 3  1]
 [-3  7]]
Multiplication:
 [[ 2 -2]
 [ 0 12]]
Subtraction:
 [[ 4 -7]
 [ 6  1]]


### 2

In [5]:
import numpy.linalg as LA
A=np.array([[2,-1],[0,3]])
#calculate determinant
D=LA.det(A)
#print determinant
print(f"Determinant:",D)
#invertible checking
if(D!=0):
    print("Invertible")
    #calculate inverse
    I=LA.inv(A)
    print(f"Inverse:\n",I)
else:
    print("Non-Invertible")   



Determinant: 6.0
Invertible
Inverse:
 [[0.5        0.16666667]
 [0.         0.33333333]]


### 3

In [7]:
C=np.array([[4,1],[-2,1]])
#Calculate Eigenvalues and Eigen vector
eva,eve = np.linalg.eig(C)
#Display the values
print(f"C:\n",C)
print(f"Eigenvalue:",eva[0])
print(f"Eigenvector:",eve[:,0])

C:
 [[ 4  1]
 [-2  1]]
Eigenvalue: 3.0
Eigenvector: [ 0.70710678 -0.70710678]


### 4

In [8]:
# Define the feature matrix X 
X=np.array([[1, 4, 1.5, 100],   # Car 1 features (with bias term),bias term le if inputs 0 cha bhane ni output dincha
              [1, 6, 2.0, 150]])  # Car 2 features (with bias term)
# Define the price vector y
# Prices of car 1 and car 2
y=np.array([20, 30])  
# Compute the coefficient vector b using the normal equation with pseudo-inverse
# X^T is the transpose of X
X_tp=X.T  
# Using pseudo-inverse instead of regular inverse to handle singular matrix
# Normal equation with pseudo-inverse, @ le matrix multiplication garcha
b=np.linalg.pinv(X_tp@X) @X_tp@y  
 # 1 for the bias term ,feature vector of car 3 ho
car3_features=np.array([1, 8, 3.0, 200]) 
#  X.T*b=y
predicted_price=car3_features@b  
print(f"Predicted price of car3:{predicted_price:.5f}")

Predicted price of car3:40.00080
